### ISSUE TITLE
DiscordBee Not detected/working - Windows 11

### ISSUE THREAD

**Issue by Tyto-le-Alba** [sll552/DiscordBee#135]
FreDiscord does not recognize or detect MusicBee with the DiscordBee plugin installed. 

1. Install DiscordBee
2. Restart MusicBee
3. Launch Discord

**Expected behavior**
Music Bee is detected and displays the current song.

**Screenshots**
![image](https://user-images.githubusercontent.com/6422431/177024366-18090532-b0e3-4ee8-a7ed-61958fe9e7fc.png)
![image](https://user-images.githubusercontent.com/6422431/177024385-e757bbb4-5ef0-433b-ae4a-322e190f05bd.png)
![image](https://user-images.githubusercontent.com/6422431/177024432-207b1023-9a1d-4057-b87f-0045bece8510.png)
![image](https://user-images.githubusercontent.com/6422431/177024462-da0f0c60-f0f3-489c-9197-78038f8a2cd8.png)

**Environment (please complete the following information):**
 - MusicBee Version: 3.4.8033
 - Plugin Version: 2.2.1
 - Windows 11

**Additional context**

**Comment by sll552** [comment]
Is there anything in `Help -> Support -> Error Log` ?

**Comment by Tyto-le-Alba** [comment]
No, "No errors have been logged".

**Comment by Summer-1999** [comment]
Did you try clicking your name and check the status? 

I think it's normal to not have it above your username and the "games detected" page like an actual game would, mine has never been there.

**Comment by catgirlmutant** [comment]
I believe I have a similar issue but in my case error logs related to discordbee showed up:

17/10/2022 7:20:52 pm - 10.0.22621.0 - 3.5.8150.17011D - System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at MusicBeePlugin.Plugin.GenerateMetaDataDictionary(String fileUrl)
   at MusicBeePlugin.Plugin.UpdateDiscordPresence(PlayState playerGetPlayState)
   at MusicBeePlugin.Plugin.ReceiveNotification(String _, NotificationType type)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at #=zoKrwgApZgrpBSGsmYQ==.#=zSBf26vMYulKX()

**Comment by catgirlmutant** [comment]
17/10/2022 7:20:52 pm - 10.0.22621.0 - 3.5.8150.17011D - System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at MusicBeePlugin.Plugin.GenerateMetaDataDictionary(String fileUrl)
   at MusicBeePlugin.Plugin.UpdateDiscordPresence(PlayState playerGetPlayState)
   at MusicBeePlugin.Plugin.ReceiveNotification(String _, NotificationType type)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at #=[redacted in case of any sensitive info, I'll send it here if it helps]

**Comment by catgirlmutant** [comment]
I have a similar problem but errors related to discordbee showed up in my case:

17/10/2022 7:20:52 pm - 10.0.22621.0 - 3.5.8150.17011D - System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
at MusicBeePlugin.Plugin.GenerateMetaDataDictionary(String fileUrl)
at MusicBeePlugin.Plugin.UpdateDiscordPresence(PlayState playerGetPlayState)
at MusicBeePlugin.Plugin.ReceiveNotification(String _, NotificationType type)
--- End of inner exception stack trace ---
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at #=[redacted in case of any sensitive info, I'll send it here if it helps]

**Comment by viralhysteria** [comment]
just chiming in to mention i'm having the same exact issue with the same exact error log

**Comment by catgirlmutant** [comment]
> just chiming in to mention i'm having the same exact issue with the same exact error log
> 
> update: not sure what happened, but it randomly decided to start working today. that being said, i still did have the same log output as catgirl when it was not working.

hmmm that's weird... did you remember doing anything else or did it just happened to work again?

**Comment by viralhysteria** [comment]
The only thing I recall doing is redeleting the "2.x.x" files as advised, but they had already been replaced, so I was just re-replacing the 3.x files with the same 3.x files. Other than that, all I did was restart my computer entirely for windows updates.

**Comment by Tyto-le-Alba** [comment]
Am an idiot. Had the files still in the "DiscordBee" folder, after extracting them from the zip. Placed them all in the root directory of the plugins folder, as the instructions say, et viola, it worked.
