### ISSUE TITLE
Frequent Crashes

### ISSUE THREAD

**Issue by Fivda** [sll552/DiscordBee#157]
Unsure why, but since today, despite not having applied any change to my MB since yesterday, i have been having those very frequent errors that make MusicBee force-shutdown. Sorry for the french in the log, not sure why it's there. It just happens out of the blue, and it doesn't seem to be triggered by a specific user input, but maybe i'm wrong. I haven't tried to restart my PC yet, but...
I did tweak DiscordBee around yesterday and it's literally in the crash report so

```
MusicBee v3.4.8033.18564D  (Win10.0), 28 juil. 2022 15:10:

System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à MusicBeePlugin.DiscordTools.DiscordClient.<UploadArtwork>d__22.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   à System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   à System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   à System.Threading.ThreadPoolWorkQueue.Dispatch()
   à System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by IanPrigmore** [comment]
I get the same error message. From what I can tell, the crash consistently happens when I play a song for which the album art has not been uploaded before, and pause it before the upload is completed. I get the same error code, shown below.

To recreate:

-Disable "show presence when no music is playing" in plugin settings
-Play any album that hasn't been uploaded before
-Pause after a couple seconds, before the image updates on discord, this should cause a crash.

```
MusicBee v3.5.8150.17011D  (Win10.0), 28 Jul 2022 20:27:

System.NullReferenceException: Object reference not set to an instance of an object.
   at MusicBeePlugin.DiscordTools.DiscordClient.<UploadArtwork>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by sll552** [comment]
Could you try https://ci.appveyor.com/api/buildjobs/dlkj8jbry0tj0mh5/artifacts/DiscordBee-Release--296.zip ?

**Comment by Fivda** [comment]
> Could you try https://ci.appveyor.com/api/buildjobs/dlkj8jbry0tj0mh5/artifacts/DiscordBee-Release--296.zip ?

Tried to play an album that wasn't cached yet, quickly paused, and the crash still happens.

`MusicBee v3.4.8033.18564D  (Win10.0), 30 juil. 2022 23:10:

System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à MusicBeePlugin.DiscordTools.DiscordClient.<UploadArtwork>d__22.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   à System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   à System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   à System.Threading.ThreadPoolWorkQueue.Dispatch()
   à System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()`

**Comment by sll552** [comment]
can you post a screenshot of your settings (you can blur the IDs)

**Comment by Fivda** [comment]
> can you post a screenshot of your settings (you can blur the IDs)

![image](https://user-images.githubusercontent.com/53372693/181996518-277f273f-110f-4c25-b6a3-480511a3b0d0.png)

**Comment by sll552** [comment]
now this pls https://ci.appveyor.com/api/buildjobs/kvo6xvk1o5lkf793/artifacts/DiscordBee-Release--297.zip

**Comment by Fivda** [comment]
> now this pls https://ci.appveyor.com/api/buildjobs/kvo6xvk1o5lkf793/artifacts/DiscordBee-Release--297.zip

very sorry, completely forgot to reply. Seems like it's working!
