### ISSUE TITLE
I can't save settings or restore to default

### ISSUE THREAD

**Issue by jackofthecreek** [sll552/DiscordBee#185]
Whenever I click on Restore Defaults or Save and Close it gives me this error:

System.NullReferenceException: Object reference not set to an instance of an object.
   at MusicBeePlugin.Settings.SetIfChanged[T](String fieldName, T value)
   at MusicBeePlugin.Settings.set_ImgurClientId(String value)
   at MusicBeePlugin.UI.SettingsWindow.buttonSaveClose_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

I'm using MusicBee version 3.4.8033 Store and this error happens on both DiscordBee version 3.0.3 and 3.0.4

I tried reinstalling both DiscordBee AND MusicBee multiple times, downgraded DiscordBee's version to 3.0.3 and no matter what I get this error. Are there any other ways to fix this?
(this is my very first bug report in anywhere so im sorry if its a bit clunky)

**Comment by sll552** [comment]
could you try https://ci.appveyor.com/api/buildjobs/so3a7xiew8ameprt/artifacts/DiscordBee-Release--326.zip ?

If it doesn't work, do you have a kind of special locale in windows like in #163 ? Also pls send me a screenshot of your settings when you try to press save.

**Comment by jackofthecreek** [comment]
> could you try https://ci.appveyor.com/api/buildjobs/so3a7xiew8ameprt/artifacts/DiscordBee-Release--326.zip ?

this worked!!! thanks a lot
i did change the system locale before replacing the discordbee release though

**Comment by sll552** [comment]
Could you also test with the original locale? Only if that's not too much work.

**Comment by jackofthecreek** [comment]
apologies for late reply but no sorry i cant im scared thatll mess it up again
