### ISSUE TITLE
Unable to initialise plugin

### ISSUE THREAD

**Issue by Realswitzer** [sll552/DiscordBee#200]
**Describe the bug**
While trying to enable Discordbee, after having to reinstall Musicbee due to it crashing constantly, plugin does not work.
Receive error saying "Unable to initialise plugin: mb_DiscordBee.dll" with reason "Exception has been thrown by the target of an invocation."

**To Reproduce**
1. Download discordbee and put in Plugins folder
2. Open Musicbee and try to enable plugin in Preferences > Plugins
3. See error

**Expected behavior**
The plugin would be enabled.

**Screenshots**
![image](https://user-images.githubusercontent.com/39711351/222852900-10b68dba-1348-4430-81ef-6d6f2a4192dd.png)
![image](https://user-images.githubusercontent.com/39711351/222852961-6d12d74c-ca2d-4b1d-8be3-e904dda834b4.png)

**Environment (please complete the following information):**
 - MusicBee Version: 3.5.8447 Installer Edition on Windows 10
 - Plugin Version: 3.0.4

**Additional context**
While I looked for another issue that mentioned this, plugin version 3.0.7 was linked but am unable to download as it's old and not hosted on the server.

**Comment by Suppression345** [comment]
Hi there. I have been having this exact same issue. I've tried contacting the DiscordBee server about it, but my efforts are to no avail so far. Any updates?

**Comment by sll552** [comment]
Please look in the error log of musicbee if there is an exception logged and post it here

**Comment by Realswitzer** [comment]
`3/10/2023 2:58:13 PM - 10.0.19044.0 - 3.5.8447.35892D - System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Runtime.Serialization.SerializationException: There was an error deserializing the object of type MusicBeePlugin.Settings. The data at the root level is invalid. Line 1, position 1. ---> System.Xml.XmlException: The data at the root level is invalid. Line 1, position 1.
   at System.Xml.XmlExceptionHelper.ThrowXmlException(XmlDictionaryReader reader, String res, String arg1, String arg2, String arg3)
   at System.Xml.XmlUTF8TextReader.Read()
   at System.Xml.XmlBaseReader.IsStartElement()
   at System.Xml.XmlBaseReader.IsStartElement(XmlDictionaryString localName, XmlDictionaryString namespaceUri)
   at System.Runtime.Serialization.XmlReaderDelegator.IsStartElement(XmlDictionaryString localname, XmlDictionaryString ns)
   at System.Runtime.Serialization.XmlObjectSerializer.IsRootElement(XmlReaderDelegator reader, DataContract contract, XmlDictionaryString name, XmlDictionaryString ns)
   at System.Runtime.Serialization.DataContractSerializer.InternalIsStartObject(XmlReaderDelegator reader)
   at System.Runtime.Serialization.DataContractSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   --- End of inner exception stack trace ---
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObject(XmlDictionaryReader reader)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObject(Stream stream)
   at MusicBeePlugin.Settings.Load(String filePath)
   at MusicBeePlugin.Settings.GetInstance(String filePath)
   at MusicBeePlugin.Plugin.Initialise(IntPtr apiInterfacePtr)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at #=z5PgYRDH$zNo7WhzgWg==..ctor(#=z4$90odPQW5oVh9588w== #=zeHK_e
$g=)`
Unfortunately, due to GitHub upload limitations I have to use a double extension to send the full log here.
[ErrorLog.dat.txt](https://github.com/sll552/DiscordBee/files/10946045/ErrorLog.dat.txt)

**Comment by sll552** [comment]
Ok looks like your settings file got corrupted somehow.

Just delete `%APPDATA%\MusicBee\DiscordBee\DiscordBee.settings` and try again

**Comment by Realswitzer** [comment]
Oh, it worked now. Unsure what caused it to get corrupted though. Will close, reopen if needed.
